name: Build iOS IPA and Android APK workflow

on: push

jobs:
  build:
    name: Build iOS IPA and Android APK
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive


      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          
          
      - name: Build APK
        run: |
          mkdir -p android/app/key
          echo ${{ secrets.MSB_ANDROID_KEYSTORE_JKS }} | base64 --decode > android/app/key/msb_app.jks
          flutter build apk -P=storePassword=${{ secrets.MSB_ANDROID_KEY0_PASSWORD }} -P=keyPassword=${{ secrets.MSB_ANDROID_KEY0_PASSWORD }} \
            --dart-define=MSB_WEBAPP_URL=https://msb.cloudns.asia/webapp --dart-define=MSB_BOT_NAME=moe_sticker_bot \
            --target-platform android-arm,android-arm64
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/msb_app.apk

      - name: Upload a APK Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: msb_app.apk
          path: build/app/outputs/flutter-apk/msb_app.apk
          
          
      - name: Build IPA
        run: |
          flutter build ios --no-codesign \
            --dart-define=MSB_WEBAPP_URL=https://msb.cloudns.asia/webapp --dart-define=MSB_BOT_NAME=moe_sticker_bot
          sh scripts/strip_payload.sh build/ios/iphoneos/Runner.app
          cd build/ios/iphoneos/
          mkdir Payload
          mv Runner.app Payload/Runner.app
          bsdtar -acvf msb_app.ipa.zip Payload
          mv msb_app.ipa.zip msb_app.ipa
          
      - name: Upload a IPA Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: msb_app.ipa
          path: build/ios/iphoneos/msb_app.ipa


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            build/app/outputs/flutter-apk/msb_app.apk
            build/ios/iphoneos/msb_app.ipa
